# Lazygit [`https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md`]
gui:
  sidePanels:
    - [files]
    - [branches]
    - [commits]
  screenMode: full

customCommands:
  - key: "<c-e>"
    command: "nvim -c NvimTreeFocus"
    context: "global"
    output: terminal
